// vue-zelda-error/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <router-view/>
    <ZeldaError :situation="zeldaSituation"
                locale="ja"
                :showTicketLink="true"
                :settings="zeldaSettings"/>
  </div>
</template>

<script lang="ts">
  import {Component, Vue} from "vue-property-decorator";
  import HelloWorld from "./components/HelloWorld.vue";
  import {
    MyZeldaDBIntegration,
    MyZeldaErrorLabels,
    MyZeldaIssueExtension,
    MyZeldaNotificationIntegration,
    MyZeldaStyles,
    MyZeldaTicketIntegration,
  } from "./my-zelda-implementations";
  import {ZeldaErrorSettings} from "./zelda-error/common/types/zelda-error-property-types";
  import ZeldaError from "./zelda-error/ZeldaError.vue";

  @Component({
    components: {
      HelloWorld,
      ZeldaError,
    },
  })
  export default class App extends Vue {
    public get zeldaSituation() {
      return this.$route.name;
    }

    public zeldaSettings: ZeldaErrorSettings = {
      styles: MyZeldaStyles,
      issueExtension: MyZeldaIssueExtension,
      ticketIntegration: MyZeldaTicketIntegration,
      notificationIntegration: MyZeldaNotificationIntegration,
      dbIntegration: MyZeldaDBIntegration,
      localeLabels: MyZeldaErrorLabels,
    };
  }
</script>

<style lang="scss">
  #app {
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
</style>

// angular-zelda-error/src/app/app.component.ts
import {Component} from '@angular/core';
import {
  MyZeldaDBIntegration,
  MyZeldaErrorLabels,
  MyZeldaIssueExtension,
  MyZeldaNotificationIntegration,
  MyZeldaStyles,
  MyZeldaTicketIntegration
} from "./my-zelda-implementations";
import {ZeldaErrorSettings} from "./zelda-error/common/types/zelda-error-property-types";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Angular ZELDA_ERROR';
  zeldaSituation: string = '';
  zeldaSettings: ZeldaErrorSettings = {
    styles: MyZeldaStyles,
    issueExtension: MyZeldaIssueExtension,
    ticketIntegration: MyZeldaTicketIntegration,
    notificationIntegration: MyZeldaNotificationIntegration,
    dbIntegration: MyZeldaDBIntegration,
    localeLabels: MyZeldaErrorLabels,
  };

  onRouterActivate($event) {
    this.zeldaSituation = $event.constructor.name;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <zelda-error [situation]="zeldaSituation"
               [settings]="zeldaSettings"
               [locale]="'ja'"
               [showTicketLink]="false"></zelda-error>
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo"
       src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>

<router-outlet (activate)="onRouterActivate($event)"></router-outlet>
