// vue-zelda-error/src/zelda-error/ZeldaError.vue
import {ZeldaIssueStatus} from "./types/zelda-error-types";
<template>
  <div class='zelda-error' v-if="!hideEternally">
    <div class='invisible-background'
         @click="onToggleZelda"
         v-if="open"></div>

    <div class="zelda-button"
         :class="[`bg-${iconBackground}`]"
         @click="onToggleZelda"
         :style="{
         top: `${settings.styles.zeldaButtonTop || 24}px`,
         right: `${settings.styles.zeldaButtonRight || 24}px`
         }">
      <img src="./common/triangle.png"/>
      <span>{{issues.filter(issue => issue.status === 'open'/*ZeldaIssueStatus.open*/).length}}</span>
    </div>

    <div class="zelda-panel"
         :class="{open: open}"
         :style="{
    top: `${settings.styles.zeldaButtonTop || 24}px`,
    right: `${settings.styles.zeldaButtonRight || 24}px`,
    width: `${settings.styles.panelWidth || 400}px`,
    height: `${settings.styles.panelHeight || 400}px`,
    }">

      <div class='header' :style="{width: settings.styles.panelWidth - 20}">
        <span>[{{situation}}]</span>
        <div class='hide-button bg-info'
             @click="onHideEternally">
          {{labels.hideButtonPrefix}}<img src="./common/triangle.png"/>{{labels.hideButtonSuffix}}
        </div>
      </div>

      <h3 class='loading' v-if="loading">Loading...</h3>

      <div class='issues' v-if="!loading">
        <div class='issue' v-for="button in issueButtons"
             :class="[(button.issue.status === 'open' /*ZeldaIssueStatus.open*/) ? 'open' : 'closed']"
             :key="button.issue.id">
          <div class="button"
               :class="button.classes"
               @click="onVote(button.issue)">
            {{button.label}}
          </div>
          <span class='title'>
            <a v-if="showTicketLink && button.issue.ticket != null && button.issue.ticket.url != null"
               :href="button.issue.ticket.url"
               target="_blank">#{{button.issue.ticket.id}}</a>
            <span v-else>#{{button.issue.ticket ? button.issue.ticket.id : '???'}}</span>
            {{' ' + button.issue.title}}
          </span>
        </div>
      </div>

      <div class='footer'>
        <input title="issueTitle"
               :placeholder="labels.formPlaceholder"
               :value="issueTitle"
               @change="onChangeTitle"
               :disabled="issueSending"/>
        <div>
          <button class="request bg-warn"
                  :class="[issueSending ? 'disabled' : '']"
                  :disabled="issueSending"
                  @click="onAddIssue('request' /*ZeldaIssueType.request*/)">
            <span>{{labels.registerRequest}}</span>
          </button>
          <button class="error bg-error"
                  :class="[issueSending ? 'disabled' : '']"
                  :disabled="issueSending"
                  @click="onAddIssue('error' /*ZeldaIssueType.error*/)">
            <span>{{labels.registerError}}</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import {Component, Prop, Vue, Watch} from "vue-property-decorator";
  import {ZeldaErrorDefaultLabels, ZeldaErrorLabels} from "./common/types/zelda-error-lang-types";
  import {ZeldaErrorSettings} from "./common/types/zelda-error-property-types";
  import {ZeldaIssue, ZeldaIssueStatus, ZeldaIssueType} from "./common/types/zelda-error-types";
  import {ZeldaErrorService} from "./common/zelda-error-service";

  @Component
  export default class ZeldaError extends Vue {
    @Prop() public situation!: string;
    @Prop() public settings!: ZeldaErrorSettings;
    @Prop({default: "en"}) public locale: string;
    @Prop({default: true}) public showTicketLink: boolean;

    private labels: ZeldaErrorLabels = ZeldaErrorDefaultLabels.ja;
    private open: boolean = false;
    private loading: boolean = false;
    private iconBackground: "success" | "warn" | "error" = "success";
    private issues: ZeldaIssue[] = [];
    private voted: { [issueId: string]: boolean } = {};
    private issueTitle: string = "";
    private issueSending: boolean = false;
    private hideEternally: boolean = false;

    public created() {
      this.labels = this.settings.localeLabels[this.locale];
      this.onChangeSituation().then();
    }

    @Watch("situation")
    protected async onChangeSituation() {
      if (this.hideEternally) {
        return;
      }

      this.loading = true;

      // load issues of situation
      await ZeldaErrorService.loadIssues(this.settings, this.situation, (issues) => {
        this.issues = issues;
        this.loading = false;
        this.updateButtonBG();
      });
    }

    protected updateButtonBG() {
      if (this.issues.some((issue) => issue.status === ZeldaIssueStatus.open)) {
        if (this.issues.some((issue) => issue.type === ZeldaIssueType.error)) {
          this.iconBackground = "error";
        } else {
          this.iconBackground = "warn";
        }
      } else {
        this.iconBackground = "success";
      }
    }

    protected onToggleZelda() {
      this.open = !this.open;
    }

    protected async onVote(issue: ZeldaIssue) {
      if (issue.status !== ZeldaIssueStatus.open || this.voted[issue.id]) {
        return;
      }

      issue = this.issues.find((each: ZeldaIssue) => each.id === issue.id)!;
      ZeldaErrorService.vote(this.settings, issue).then();

      this.voted[issue.id] = true;
    }

    protected async onAddIssue(type: ZeldaIssueType | string) {
      const title = this.issueTitle.trim();
      if (title.length <= 0) {
        return;
      }

      this.issueSending = true;

      const result = await confirm(type === "error"
        ? this.labels.confirmRegisterError
        : this.labels.confirmRegisterRequest);
      if (!result) {
        this.issueSending = false;
        return;
      }

      this.addIssue(title, type as ZeldaIssueType).then();
    }

    protected async addIssue(title: string, type: ZeldaIssueType) {
      try {
        this.issueSending = true;

        const issue = await ZeldaErrorService.createIssue(
          this.settings,
          this.situation,
          title,
          type,
        );

        this.issues.push(issue);
        ZeldaErrorService.sortIssues(this.issues);

        this.issueTitle = "";
        this.voted[issue.id] = true;

      } finally {
        this.issueSending = false;
        this.updateButtonBG();
      }
    }

    protected async onHideEternally() {
      this.hideEternally = await confirm(this.labels.confirmHide);
    }

    protected onChangeTitle(event: any) {
      this.issueTitle = event.target.value;
    }

    protected get issueButtons(): any[] {
      return this.issues.map(this.toIssueButton);
    }

    protected toIssueButton(issue: ZeldaIssue): any {
      let button: any = {
        issue,
        label: "",
        classes: ["disabled", "bg-info"],
      };

      switch (issue.status) {
        case "next_patch":
          button = {
            issue,
            label: this.labels.issueWaitingPatch,
            classes: ["disabled", "bg-info"],
          };
          break;
        case "fixed":
          button = {
            issue,
            label: this.labels.issueFixed,
            classes: ["disabled", "bg-success"],
          };
          break;
        default:
          button = {
            issue,
            label: `+${issue.vote}`,
            classes: ["vote", this.voted[issue.id] ? "disabled" : "", `bg-${(issue.type === "error") ? "error" : "warn"}`],
          };
          break;
      }

      return button;
    }
  }
</script>

<style scoped lang="scss">
  @import "common/ZeldaError";
</style>

// angular-zelda-error/src/app/zelda-error/zelda-error.component.ts
import {Component, Input, OnInit, SimpleChanges} from '@angular/core';
import {ZeldaErrorDefaultLabels, ZeldaErrorLabels} from "./common/types/zelda-error-lang-types";
import {ZeldaErrorSettings} from "./common/types/zelda-error-property-types";
import {ZeldaIssue, ZeldaIssueStatus, ZeldaIssueType} from "./common/types/zelda-error-types";
import {ZeldaErrorService} from "./common/zelda-error-service";

@Component({
  selector: 'zelda-error',
  templateUrl: './zelda-error.component.html',
  styleUrls: ['./common/ZeldaError.scss']
})
export class ZeldaErrorComponent implements OnInit {
  @Input() public situation!: string;
  @Input() public settings!: ZeldaErrorSettings;
  @Input() public locale: string = 'en';
  @Input() public showTicketLink: boolean = true;

  private labels: ZeldaErrorLabels = ZeldaErrorDefaultLabels.ja;
  private open: boolean = false;
  private loading: boolean = false;
  private iconBackground: 'success' | 'warn' | 'error' = 'success';
  private issues: ZeldaIssue[] = [];
  private voted: { [issueId: string]: boolean } = {};
  private issueTitle: string = '';
  private issueSending: boolean = false;
  private hideEternally: boolean = false;

  ngOnInit() {
    this.labels = this.settings.localeLabels[this.locale];
  }

  async ngOnChanges(changes: SimpleChanges) {
    if (this.hideEternally || !changes.situation || !this.situation) {
      return;
    }

    this.loading = true;

    // load issues of situation
    await ZeldaErrorService.loadIssues(this.settings, this.situation, (issues) => {
      this.issues = issues;
      this.loading = false;
      this.updateButtonBG();
    });
  }

  updateButtonBG() {
    if (this.issues.some((issue) => issue.status === ZeldaIssueStatus.open)) {
      if (this.issues.some((issue) => issue.type === ZeldaIssueType.error)) {
        this.iconBackground = 'error';
      } else {
        this.iconBackground = 'warn';
      }
    } else {
      this.iconBackground = 'success';
    }
  }

  onToggleZelda() {
    this.open = !this.open;
  }

  async onVote(issue: ZeldaIssue) {
    if (issue.status !== ZeldaIssueStatus.open || this.voted[issue.id]) {
      return;
    }

    issue = this.issues.find((each: ZeldaIssue) => each.id === issue.id);
    ZeldaErrorService.vote(this.settings, issue).then();

    this.voted[issue.id] = true;
  }

  onChangeTitle(issueTitle: string) {
    this.issueTitle = issueTitle;
  }

  async onAddIssue(type: ZeldaIssueType | string) {
    const title = this.issueTitle.trim();
    if (title.length <= 0) {
      return;
    }

    this.issueSending = true;

    const result = await confirm(type === 'error'
      ? this.labels.confirmRegisterError
      : this.labels.confirmRegisterRequest);
    if (!result) {
      this.issueSending = false;
      return;
    }

    this.addIssue(title, type as ZeldaIssueType).then();
  }

  async addIssue(title: string, type: ZeldaIssueType) {
    try {
      this.issueSending = true;

      const issue = await ZeldaErrorService.createIssue(
        this.settings,
        this.situation,
        title,
        type,
      );

      this.issues.push(issue);
      ZeldaErrorService.sortIssues(this.issues);

      this.issueTitle = '';
      this.voted[issue.id] = true;

    } finally {
      this.issueSending = false;
      this.updateButtonBG();
    }
  }

  async onHideEternally() {
    this.hideEternally = await confirm(this.labels.confirmHide);
  }

  get openIssueLength(): number {
    return this.issues.filter((issue) => issue.status === ZeldaIssueStatus.open).length;
  }

  get issueButtons(): any[] {
    return this.issues.map(this.toIssueButton);
  }

  toIssueButton = (issue: ZeldaIssue): any => {
    let button: any = {
      issue,
      label: '',
      classes: ['disabled', 'bg-info'],
    };

    switch (issue.status) {
      case 'next_patch':
        button = {
          issue,
          label: this.labels.issueWaitingPatch,
          classes: ['disabled', 'bg-info'],
        };
        break;
      case 'fixed':
        button = {
          issue,
          label: this.labels.issueFixed,
          classes: ['disabled', 'bg-success'],
        };
        break;
      default:
        button = {
          issue,
          label: `+${issue.vote}`,
          classes: ['vote', this.voted[issue.id] ? 'disabled' : '', `bg-${(issue.type === 'error') ? 'error' : 'warn'}`],
        };
        break;
    }

    return button;
  }
}

<div class='zelda-error' *ngIf="!hideEternally">
  <div class='invisible-background'
       (click)="onToggleZelda()"
       *ngIf="open"></div>

  <div class="zelda-button bg-{{iconBackground}}"
       (click)="onToggleZelda()"
       [style.top]="(settings.styles.zeldaButtonTop || 24) + 'px'"
       [style.right]="(settings.styles.zeldaButtonRight || 24) + 'px'">
    <img src="assets/zelda-error/triangle.png"/>
    <span>
      {{openIssueLength}}
    </span>
  </div>

  <div class="zelda-panel"
       [class.open]="open"
       [style.top]="(settings.styles.zeldaButtonTop || 24) + 'px'"
       [style.right]="(settings.styles.zeldaButtonRight || 24) + 'px'"
       [style.width]="(settings.styles.panelWidth || 400) + 'px'"
       [style.height]="(settings.styles.panelHeight || 400) + 'px'">

    <div class='header'
         [style.width]="(settings.styles.panelWidth - 20) + 'px'">
      <span>[{{situation}}]</span>
      <div class='hide-button bg-info'
           (click)="onHideEternally().then()">
        {{labels.hideButtonPrefix}}
        <img src="assets/zelda-error/triangle.png"/>
        {{labels.hideButtonSuffix}}
      </div>
    </div>

    <h3 class='loading' *ngIf="loading">Loading...</h3>

    <div class='issues' *ngIf="!loading">
      <div class="issue {{(button.issue.status === 'open') ? 'open' : 'closed'}}"
           *ngFor="let button of issueButtons">
        <div class="button"
             [ngClass]="button.classes"
             (click)="onVote(button.issue).then()">
          {{button.label}}
        </div>
        <span class='title'>
            <a *ngIf="showTicketLink && button.issue.ticket != null && button.issue.ticket.url != null; else nolink"
               [href]="button.issue.ticket.url"
               target="_blank">#{{button.issue.ticket.id}}</a>
            <ng-template #nolink>
              <span>#{{button.issue.ticket ? button.issue.ticket.id : '???'}}</span>
            </ng-template>
            {{' ' + button.issue.title}}
          </span>
      </div>
    </div>

    <div class='footer'>
      <input title="issueTitle"
             [placeholder]="labels.formPlaceholder"
             [value]="issueTitle"
             (change)="onChangeTitle($event.target.value);"
             [disabled]="issueSending"/>
      <div>
        <button class="request bg-warn {{issueSending ? 'disabled' : ''}}"
                [disabled]="issueSending"
                (click)="onAddIssue('request').then();">
          <span>{{labels.registerRequest}}</span>
        </button>
        <button class="error bg-error {{issueSending ? 'disabled' : ''}}"
                [disabled]="issueSending"
                (click)="onAddIssue('error').then();">
          <span>{{labels.registerError}}</span>
        </button>
      </div>
    </div>
  </div>
</div>
